config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :api_calls, only: [:new, :create] do
    resources :videos, only: [:new, :create]
  end

  resources :videos, only: [:index, :show]
  resources :events, only: [:index, :create]
end

app/models/analytics_call.rb
class AnalyticsCall < ActiveRecord::Base
  has_many :video_events
  validates :events_pulled, presence: true

  scope :last_call, -> { order(created_at: :desc).first }

  def get_batch


    querier = AnalyticsQuerier.new({

      'start-date' => AnalyticsCall.last_call_date.to_s,
      'end-date'   => Date.today.to_s,
      'metrics'    => 'ga:totalEvents',
      'dimensions' => 'ga:eventAction, ga:eventLabel, ga:date',
      'filters'    => 'ga:eventCategory==Videos'

      })

    querier.authorize_with_services
    batch = querier.query_analytics

    batch

  end

  def self.last_call_date
    if AnalyticsCall.count > 0
      last_call.created_at
    else
      Date.new(2015,1,1)
    end
  end

end

app/models/api_call.rb
class ApiCall < ActiveRecord::Base
  has_many :videos

  include HTTParty
  BASE_URI = "http://confreaks.tv/api/v1/"

  validates :page, presence: true

  def get_result
    JSON.parse(call_api.response.body)
  rescue
    "api unavailable from #{construct_url}"
  end

  def construct_url
    url = BASE_URI + page + determine_params
    url
  end

  def determine_params
    if sort || limit
      url = "?"
      if sort && limit && !sort.blank? && !limit.blank?
        url += "sort=#{sort}&limit=#{limit}"
      elsif sort && !sort.blank? && !limit
        url += "sort=#{sort}"
      elsif limit && !limit.blank? && (!sort || sort.blank?)
        url += "limit=#{limit}"
      end
    else
      url = ""
    end
    url
  end

  def call_api
    HTTParty::get(construct_url)
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :api_call
  has_many :video_events
  
  validates :title, presence: true
end

app/models/video_event.rb
class VideoEvent < ActiveRecord::Base
  belongs_to :video
  belongs_to :analytics_call
end

app/controllers/api_calls_controller.rb
class ApiCallsController < ApplicationController
  def new
    @api_call = ApiCall.new
  end

  def create
    @api_call = ApiCall.new(api_call_params)

    if @api_call.save
      flash[:notice] = "Call saved."
      redirect_to new_api_call_video_path(@api_call)
    else
      flash[:alert] = "Could not save API call."
      render 'new'
    end
  end

  protected

  def api_call_params
    params.require(:api_call).permit(:page, :sort, :limit)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @video_events = VideoEvent.all
    @analytics_calls = AnalyticsCall.all
  end

  def create

    @analytics_call = AnalyticsCall.new
    batch = @analytics_call.get_batch

    @analytics_call.events_pulled = batch.count
    @analytics_call.save

    batch_id = @analytics_call.id

    batch.each do |video_event|
      constructor = ConstructsVideoEvent.new(video_event, batch_id)
      constructor.create!
    end

    redirect_to events_path

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
    @call_id = params[:api_call_id]
    @videos = []
    call = ApiCall.find(@call_id)
    results = call.get_result

    if results.class != String
      results.each do |result|
        constructor = ConstructsVideo.new(result)
        @videos << constructor.build
      end

      @videos.each do |video|
        video.api_call_id = @call_id
      end
    else
      flash[:alert] = "That was a bad call."
      ApiCall.find(@call_id).destroy
      redirect_to new_api_call_path
    end
  end

  def create
    @call_id = params[:api_call_id]
    @videos = []
    call = ApiCall.find(@call_id)
    results = call.get_result

    if results.class != String
      results.each do |result|
        constructor = ConstructsVideo.new(result)
        @videos << constructor.build
      end

      @videos.each do |video|
        video.api_call_id = @call_id
        video.save(video_params)
      end

      redirect_to videos_path and return
    else
      flash[:alert] = "That was a bad call!"
      ApiCall.find(@call_id).destroy
      redirect_to new_api_call_path
    end
  end

  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
  end

  private

  def video_params
    params.permit(:title, :slug, :host, :embed_code, :api_call_id)
  end
end

app/helpers/api_calls_helper.rb
module ApiCallsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
  def embed(embed_code)
    source = "//youtube.com/embed/#{embed_code}?fs=1"
    content_tag(:iframe, nil, src: source)
  end
end

app/views/api_calls/new.html.haml
%h1 Call.TV

= simple_form_for @api_call do |f|
  = f.input :page
  = f.input :sort
  = f.input :limit
  = f.submit 'Save'

app/views/events/create.html.erb
<%= @events %>

app/views/events/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Video Events</h1>
  </div><!-- /.col-sm-6 -->

  <div class="col-sm-6">
    <h1>
      <%= link_to "Pull Events", events_path, method: :post %>
    </h1>
  </div><!-- /.col-sm-6 -->
</div><!-- /.row -->

<div class="row">
  <div class="col-sm-6">
    <% if @video_events.any? %>
      <ul>
        <% @video_events.each do |event| %>
          <li><%= event.video.title %> | <%= event.action %> | <%= event.date %></li>
        <% end %>
      </ul>
    <% else %>
      <h3>There are no events in the database.</h3>
    <% end %>
  </div><!-- /.col-sm-6 -->

  <div class="col-sm-6">
    <% if @analytics_calls.any? %>
      <ul>
        <% @analytics_calls.each do |call| %>
          <li>brought in <%= call.events_pulled %> events on <%= call.created_at %></li>
        <% end %>
      </ul>
    <% else %>
      <h3>No calls to the Google Analytics Reporting API have been sent</h3>
    <% end %>
  </div><!-- /.col-sm-6 -->
</div><!-- /.row -->

app/views/layouts/_ga_tracking.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58401408-2', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.haml
= link_to "home", root_path
|
= link_to "call.TV", new_api_call_path
|
= link_to "all videos", videos_path
|
= link_to "events", events_path
|
%a{href: "https://desolate-fortress-9280.herokuapp.com/", target: "_blank"}
  production

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YtGaPlayground</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= render 'layouts/ga_tracking' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/header" %>

  <div class="container">
    <%= yield %>
  </div>

  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/videos/_video.html.haml
%ul
  %li
    %strong
      = link_to video.title, video_path(video)
  %li
    &nbsp;&nbsp;&nbsp;&nbsp;
    = "#{video.host} | #{video.embed_code}"

app/views/videos/index.html.haml
%h1 All Videos

= render @videos

app/views/videos/new.html.haml
= form_tag "/api_calls/#{@call_id}/videos" do
  - @videos.each do |video|
    = label_tag "title"
    = text_field_tag :title, video.title
    = label_tag "slug"
    = text_field_tag :slug, video.slug
    = label_tag "host"
    = text_field_tag :host, video.host
    = label_tag "embed_code"
    = text_field_tag :embed_code, video.embed_code
    %hr

  = submit_tag "Save"

app/views/videos/show.html.haml
.col-md-offset-2.col-md-8
  .video-container
    = embed(@video.embed_code)